# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3fd85106af2084d70019edd69bd0c75e7b9ca4c12f54003dba2cbe6b5a2b9b21aff136ee6790dc512e10b803ab3c79e897f6dcf316b7833a083a986f9ded549

test:
  secret_key_base: 2de2b272e21f8759d5541b312153f13050ca5a57a38ad788d29fee6535aeeeb2976c7ccac4048c5b2f7edc5d6acbef531566c6f8ffdf93e4137ffc8413c35f6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
